name: SilenceKitDemo
options:
  bundleIdPrefix: com.chen
  deploymentTarget:
    iOS: 17.0

packages:
  SilenceKit:
    url: https://github.com/hechen/SilenceKit.git
    from: 1.0.0

targets:
  SilenceKitDemo:
    type: application
    platform: iOS
    sources:
      - SilenceKitDemo
    dependencies:
      - package: SilenceKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.chen.silencekitdemo
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 1,2
        GENERATE_INFOPLIST_FILE: true
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 96M48MTC67
        CODE_SIGN_STYLE: Automatic
